### ISSUE TITLE
Add Fabric.io for crash reporting

### ISSUE THREAD

**Issue by prabirmsp** [GrinnellAppDev/DB-Android#23]

**Comment by 370417** [comment]
Fabric is already configured according to the plugin, and crashlytics already is reporting crashes from us testing the app. The API key is [visible on github](https://github.com/GrinnellAppDev/DB-Android/blob/f9420cbf14b269880ccf472faee3143a39c36888/app/src/main/AndroidManifest.xml#L33), is that really alright?

Also, crashlytics has now been updated on the albert/build branch.
